### ISSUE TITLE
Parse restClient

### ISSUE THREAD

**Issue by chandrabezzo** [parse-community/Parse-SDK-Android#1019]
E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: android.package, PID: 3767
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at okhttp3.internal.Util.<clinit>(Util.java:87)
        at okhttp3.internal.Util.immutableList(Util.java:234)
        at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:124)
        at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:449)
        at com.parse.ParsePlugins.restClient(ParsePlugins.java:116)
        at com.parse.Parse.getEventuallyQueue(Parse.java:410)
        at com.parse.Parse.access$000(Parse.java:39)
        at com.parse.Parse$1.call(Parse.java:165)
        at com.parse.Parse$1.call(Parse.java:162)
        at bolts.Task$4.run(Task.java:357)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

I got this error, should I do to resolve?

**Comment by Jawnnypoo** [comment]
You'll need to compile your project with Java 8 https://developer.android.com/studio/write/java8-support
