### ISSUE TITLE
App crashes after adding dependencies and maven

### ISSUE THREAD

**Issue by Sayum24** [parse-community/Parse-SDK-Android#1135]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Android SDK](https://github.com/parse-community/Parse-SDK-Android/releases). 

### Issue Description
I just added the dependencies to my code in the build.gradle (app):
`    //back4app https://github.com/parse-community/Parse-SDK-Android
    implementation "com.github.parse-community.Parse-SDK-Android:parse:2.0.3"
    // for Kotlin extensions support (optional)
    implementation "com.github.parse-community.Parse-SDK-Android:ktx:2.0.3"`

And added the following repo in the build.gradle (project):
`        maven { url "https://jitpack.io" }`

After that I tried to run the app but it crashes right after start with the following error:
`D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jusaw.curveradio, PID: 12032
    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
        at androidx.appcompat.app.AppCompatDelegateImpl.onPostCreate(AppCompatDelegateImpl.java:530)
        at androidx.appcompat.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:151)
        at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1373)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3321)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

The issue must be the implementation in build.gradle (app), because after adding the repo the app still runs.

### Environment

Parse Android SDK
- SDK version: `Android 10`
- Operating system version: `Windows 10`

Server
- Parse Server version: `2.0.3`
- Operating system: `n/a`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `n/a`

Database
- System (MongoDB or Postgres): `n/a`
- Database version: `n/a`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `n/a
- `

**Comment by Sayum24** [comment]
I checked the maven thing, now it works
