### ISSUE TITLE
ConcurrentModificationException in ParseObject.isDirty()

### ISSUE THREAD

**Issue by akonior** [parse-community/Parse-SDK-Android#154]
Got this exception when calling `isDirty()` on an instance of `ParseObject`

```
Caused by: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
       at java.util.HashMap$ValueIterator.next(HashMap.java:838)
       at com.parse.ParseTraverser.traverseInternal(ParseTraverser.java:87)
       at com.parse.ParseTraverser.traverse(ParseTraverser.java:137)
       at com.parse.ParseObject.collectDirtyChildren(ParseObject.java:2415)
       at com.parse.ParseObject.access$1400(ParseObject.java:52)
       at com.parse.ParseObject$36.visit(ParseObject.java:2469)
       at com.parse.ParseTraverser.traverseInternal(ParseTraverser.java:54)
       at com.parse.ParseTraverser.traverseInternal(ParseTraverser.java:88)
       at com.parse.ParseTraverser.traverse(ParseTraverser.java:137)
       at com.parse.ParseObject.collectDirtyChildren(ParseObject.java:2415)
       at com.parse.ParseObject.collectDirtyChildren(ParseObject.java:2486)
       at com.parse.ParseObject.hasDirtyChildren(ParseObject.java:1173)
       at com.parse.ParseObject.isDirty(ParseObject.java:1191)
       at com.parse.ParseObject.isDirty(ParseObject.java:1185)
       ...
```

I'm using `com.parse:parse-android:1.10.2`

**Comment by wangmengyan95** [comment]
Hi @akonior , this exception happen because when we try to save a ParseObject or check whether a ParseObject is dirty or not, we traverse its children to make sure all of them have been saved/checked, when we use the iterator to traverse a map under the ParseObject, the map is also being revised by no only this iterator. Since you also hold the reference of this map, could you take a look whether you revise the map under ParseObject when you try to save this ParseObject or call `isDirty()`?

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently / it seems it may have been solved by a PR.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
