### ISSUE TITLE
StrictMode: Initialise off the Main Thread.

### ISSUE THREAD

**Issue by chrisjenx** [parse-community/Parse-SDK-Android#37]
When calling the `initialize` method, I would hope that any IO would be done off the UI thread.
Seen as the library is build on bolts, It would be safe assumption to make sure that any touching of resources should be handled by a task.

It would also be prudent to queue up subsequent tasks until the `initialize` is fully completed.

``` bash
5660-5660/com.owlr.tv.debug D/StrictMode﹕ StrictMode policy violation; ~duration=31 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=2591 violation=2
            at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
            at libcore.io.BlockGuardOs.access(BlockGuardOs.java:67)
            at java.io.File.doAccess(File.java:283)
            at java.io.File.exists(File.java:363)
            at android.app.ContextImpl.getDir(ContextImpl.java:2229)
            at android.content.ContextWrapper.getDir(ContextWrapper.java:257)
            at android.net.SSLSessionCache.<init>(SSLSessionCache.java:97)
            at com.parse.ParseRequest.initialize(ParseRequest.java:137)
            at com.parse.Parse.initialize(Parse.java:184)
            at com.owlr.io.ParseAPIWrapper.init(ParseAPIWrapper.java:81)
```

The prior strict mode violation occurs when calling:

``` java
Parse.enableLocalDatastore(application);
Parse.initialize(application, metaDataManager.getParseAppId(),
        metaDataManager.getParseClientKey());
```

Either that or its made a bit clearer that IO operations happen on `initialize`.

**Comment by YaoPersonal** [comment]
If we merge #180, we no longer have read violation causing from RESTclient. But we still have other read and write violation in other place.

For read violation:
>android.content.ContextWrapper.getCacheDir(ContextWrapper.java:232)
>com.parse.ParseKeyValueCache.initialize(ParseKeyValueCache.java:56)
>com.parse.Parse.initialize(Parse.java:207)

For write violation:
>java.io.OutputStream.write(OutputStream.java:82)
>com.parse.Parse.checkCacheApplicationId(Parse.java:388)
>com.parse.Parse.initialize(Parse.java:211)

**Comment by alexblack** [comment]
+1

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
