### ISSUE TITLE
ParseException: The number for rate is too large

### ISSUE THREAD

**Issue by alexblack** [parse-community/Parse-SDK-Android#411]
Can you offer any insight into what this means?

```
Non-fatal Exception: java.lang.Exception: Failed to sync, parse error: 111
       at com.aadhk.woinvoice.sync.SyncRunner.handleException(SyncRunner.java:93)
       at com.aadhk.woinvoice.sync.SyncRunner.access$000(SyncRunner.java:58)
       at com.aadhk.woinvoice.sync.SyncRunner$2.then(SyncRunner.java:208)
       at com.aadhk.woinvoice.sync.SyncRunner$2.then(SyncRunner.java:193)
       at bolts.Task$15.run(Task.java:917)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by com.parse.pj: The number for rate is too large
       at com.parse.ParseRequest.onResponseAsync(ParseRequest.java:270)
       at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:301)
       at com.parse.ParseRequest$3.then(ParseRequest.java:137)
       at com.parse.ParseRequest$3.then(ParseRequest.java:133)
       at bolts.Task$15.run(Task.java:917)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeAfterTask(Task.java:908)
       at bolts.Task.continueWithTask(Task.java:715)
       at bolts.Task.continueWithTask(Task.java:726)
       at bolts.Task$13.then(Task.java:818)
       at bolts.Task$13.then(Task.java:806)
       at bolts.Task$15.run(Task.java:917)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by alexblack** [comment]
I'm also seeing this error on much older versions of my app, perhaps its not an Android SDK issue but a cloud issue?

It looks like the error message is "The number for <field> is too large"

The number for balanceDue is too large 
stacktrace	com.parse.mu: The number for balanceDue is too large at com.parse.mh.a(ProGuard:391) at com.parse.lw.a(ProGuard:197) at com.parse.mk.b(ProGuard:258) at com.parse.mk.a(ProGuard:254) at a.u.run(ProGuard:825) at a.h.execute(ProGuard:105) at a.n.d(ProGuard:816) at a.n.b(ProGuard:628) at a.n.b(ProGuard:639) at a.s.b(ProGuard:731) at a.s.a(ProGuard:719) at a.u.run(ProGuard:825) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) at java.lang.Thread.run(Thread.java:818)  
errid	0930f49d-1adc-40bd-b26c-703c72485e98 
name	error

**Comment by natario1** [comment]
This really looks like a cloud issue since the error comes as output of a REST request. Going to close, feel free to reopen if you have further info
