### ISSUE TITLE
When I try to upload ".mp4" file, I got below error message

### ISSUE THREAD

**Issue by elviskuo07** [parse-community/Parse-SDK-Android#508]
```
08-02 16:32:31.744 12090-12090/E/NewPhotoActivity: Save video : 100 i/o failure
08-02 16:32:31.744 12090-12090/E/NewPhotoActivity: Save video cause : java.net.SocketException: sendto failed: EPIPE (Broken pipe)
08-02 16:32:31.744 12090-12090/E/NewPhotoActivity: Save video stack trace : com.parse.ParseRequest$ParseRequestException: i/o failure
                                                                         at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:290)
                                                                         at com.parse.ParseRequest$2.then(ParseRequest.java:145)
                                                                         at com.parse.ParseRequest$2.then(ParseRequest.java:139)
                                                                         at bolts.Task$15.run(Task.java:917)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                                                                         at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
                                                                         at libcore.io.IoBridge.sendto(IoBridge.java:515)
                                                                         at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
                                                                         at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
                                                                         at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
                                                                         at com.android.okio.Okio$1.write(Okio.java:70)
                                                                         at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
                                                                         at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
                                                                         at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:287)
                                                                         at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
                                                                         at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
                                                                         at com.parse.ParseCountingByteArrayHttpBody.writeTo(ParseCountingByteArrayHttpBody.java:40)
                                                                         at com.parse.ParseURLConnectionHttpClient.executeInternal(ParseURLConnectionHttpClient.java:49)
                                                                         at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158)
                                                                         at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
                                                                         at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
                                                                         at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
                                                                         at com.parse.ParseRequest$3.then(ParseRequest.java:136)
                                                                         at com.parse.ParseRequest$3.then(ParseRequest.java:133)
                                                                         at bolts.Task$15.run(Task.java:917)
                                                                         at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
                                                                         at bolts.Task.completeAfterTask(Task.java:908)
                                                                         at bolts.Task.continueWithTask(Task.java:715)
                                                                         at bolts.Task.continueWithTask(Task.java:726)
                                                                         at bolts.Task$13.then(Task.java:818)
                                                                         at bolts.Task$13.then(Task.java:806)
                                                                         at bolts.Task$15.run(Task.java:917) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                         at java.lang.Thread.run(Thread.java:818) 
                                                                      Caused by: android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
                                                                         at libcore.io.Posix.sendtoBytes(Native Method)
                                                                         at libcore.io.Posix.sendto(Posix.java:176)
                                                                         at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
                                                                         at libcore.io.IoBridge.sendto(IoBridge.java:513)
                                                                         at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504) 
                                                                         at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37) 
                                                                         at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266) 
                                                                         at com.android.okio.Okio$1.write(Okio.java:70) 
                                                                         at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116) 
                                                                         at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44) 
                                                                         at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:287) 
                                                                         at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116) 
                                                                         at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131) 
                                                                         at com.parse.ParseCountingByteArrayHttpBody.writeTo(ParseCountingByteArrayHttpBody.java:40) 
                                                                         at com.parse.ParseURLConnectionHttpClient.executeInternal(ParseURLConnectionHttpClient.java:49) 
                                                                         at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158) 
                                                                         at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115) 
                                                                         at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147) 
                                                                         at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122) 
                                                                         at com.parse.ParseRequest$3.then(ParseRequest.java:136) 
                                                                         at com.parse.ParseRequest$3.then(ParseRequest.java:133) 
                                                                         at bolts.Task$15.run(Task.java:917) 
                                                                         at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105) 
                                                                         at bolts.Task.completeAfterTask(Task.java:908) 
                                                                         at bolts.Task.continueWithTask(Task.java:715) 
                                                                         at bolts.Task.continueWithTask(Task.java:726) 
                                                                         at bolts.Task$13.then(Task.java:818) 
                                                                         at bolts.Task$13.then(Task.java:806) 
                                                                         at bolts.Task$15.run(Task.java:917) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                         at java.lang.Thread.run(Thread.java:818) 


```

P.S.
Android Parse SDK:parse-android-1.13.2-SNAPSHOT
Android Version: 5.0.2

**Comment by elviskuo07** [comment]
```
byte[] videoBytes = null;
try {
    FileInputStream fis = new FileInputStream(new File(pathToFile));
    ByteArrayOutputStream baos = new ByteArrayOutputStream();

    byte[] buf = new byte[1024];
    int n;
    while (-1 != (n = fis.read(buf)))
    baos.write(buf, 0, n);

    videoBytes = baos.toByteArray();
    baos.close();
} catch (IOException e) {
    Log.e(TAG, e.getMessage());
} finally {
    Log.d(TAG, "videoBytes: "+ videoBytes.length);
}

ParseFile film = new ParseFile("video.mp4", videoBytes, "mp4");
film.saveInBackground(new SaveCallback() {
        @Override
        public void done(ParseException e) {
            if (e == null) {
                Log.d(TAG, "Save video");
            } else {
                Toast.makeText(getApplicationContext(), "Error saving video file: " + e.getMessage(), Toast.LENGTH_LONG).show();
                Log.e(TAG, "Save video : " +e.getCode()+" "+e.getMessage());
                Log.e(TAG, "Save video cause : " +e.getCause());
                Log.e(TAG, "Save video stack trace : " + Log.getStackTraceString(e));
            }
        }
    }, new ProgressCallback() {
        @Override
        public void done(Integer percentDone) {
            //Log.d(TAG, "video done: " + percentDone);
        }
});
```
Hi @grantland , 
This is my code, I want upload "mp4" file to parse server.
When I save parseFile in saveInBackground(), it doesn't work.
Thanks

**Comment by elviskuo07** [comment]
I upload ".mov" file in iOS with Parse-SDK-iOS is OK.
I think it's "Parse-SDK-Android" upload issue.

**Comment by grantespo** [comment]
@elviskuo07 did you find a solution for this? I'm stuck on the same thing.

**Comment by AlronGlobal** [comment]
@elviskuo07 did you get the solution for this?

**Comment by elviskuo07** [comment]
No, I think its parse issue. So we need parse official support or use AWS
solution.

On Wed, 5 Apr 2017 at 4:14 AM AlronGlobal <notifications@github.com> wrote:

@elviskuo07 <https://github.com/elviskuo07> did you get the solution for
this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ParsePlatform/Parse-SDK-Android/issues/508#issuecomment-291618463>,
or mute the thread

**Comment by flovilmart** [comment]
@elviskuo07 not sure what breaks here. What are the size of your files? Are you sure you can upload the same files (size etc...) on iOS AND Android?

**Comment by AlronGlobal** [comment]
@elviskuo07 I solved this. It was because of the file size.
