### ISSUE TITLE
ParseUser.enableRevocableSessionInBackground IllegalStateException

### ISSUE THREAD

**Issue by allonmj** [parse-community/Parse-SDK-Android#535]
I'm moving from parse to self-hosted parse-server on aws.  I'm trying to enable revocable sessions by doing the following.

`ParseUser.enableRevocableSessionInBackground().onSuccess(new Continuation<Void, Object>() {
                    @Override
                    public Object then(Task<Void> task) throws Exception {
                        continueProcessForUser(fromDeepLink);
                        return task.getResult();
                    }
                }).waitForCompletion(7, TimeUnit.SECONDS);`

I have not been able to reproduce the issue on my own, but 10% of my users are getting the following error.

Fatal Exception: java.lang.IllegalStateException: Another user controller was already registered: com.parse.NetworkUserController@8456d47
       at com.parse.ParseCorePlugins.registerUserController(ParseCorePlugins.java:108)
       at com.parse.ParseUser.enableRevocableSessionInBackground(ParseUser.java:1473)
       at com.myswimpro.android.app.ui.presenter.SplashPresenter.refresh(SplashPresenter.java:70)
       at com.myswimpro.android.app.ui.presenter.SplashPresenter.refreshView(SplashPresenter.java:61)
       at com.myswimpro.android.app.ui.activity.SplashActivity.init(SplashActivity.java:175)
       at com.myswimpro.android.app.ui.activity.SplashActivity.access$300(SplashActivity.java:38)
       at com.myswimpro.android.app.ui.activity.SplashActivity$1$1.run(SplashActivity.java:94)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5546)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

Any ideas?  To stop the crashes I'm considering just catching the exception - but I'm not sure if I should take them to login if the exception is thrown or if I should take them to main content.  Basically, can I assume they have already enabled revocable sessions if I get that IllegalStateException?

Edit : I was able to reproduce this when I turned the "Don't keep activities" option on.  I think the solution may be that I don't need to call this method every time - just once successfully.

**Comment by lxknvlk** [comment]
Hey, if im not mistaken, in the parse tutorials it says that you should invoke this method in your Application class, there there you also initialize parse itself. So yes, this is supposed to be invoked only once.

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
