### ISSUE TITLE
ParseRequestException: Invalid file upload.

### ISSUE THREAD

**Issue by karagoezt** [parse-community/Parse-SDK-Android#540]
I'm using android SDK 1.13.1 and can't store video(mp4) Files.

I always get Errorcode 130 
Message: Invalid file upload.
Stacktrace:
com.parse.ParseRequest$ParseRequestException: Invalid file upload.
at com.parse.ParseRequest.newPermanentException(ParseRequest.java:270)
at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:301)
at com.parse.ParseRequest$3.then(ParseRequest.java:137)
at com.parse.ParseRequest$3.then(ParseRequest.java:133)
at bolts.Task$15.run(Task.java:917)
at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
at bolts.Task.completeAfterTask(Task.java:908)
at bolts.Task.continueWithTask(Task.java:715)
at bolts.Task.continueWithTask(Task.java:726)
at bolts.Task$13.then(Task.java:818)
at bolts.Task$13.then(Task.java:806)
at bolts.Task$15.run(Task.java:917)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

Any ideas what i'm doing wrong ?
Thats how i create my ParseFile
final ParseFile parseFile = new ParseFile("video.mp4",videoFile);

        parseFile.saveInBackground();

Can anyone please help ?

**Comment by StuStirling** [comment]
@karagoezt any luck with this. I'm having all sorts of issues with saving files, however mine relates to images and zip files.

**Comment by rogerhu** [comment]
See: https://github.com/ParsePlatform/parse-server/issues/136

**Comment by rogerhu** [comment]
Can you try the snapshot version 1.14.1-SNAPSHOT and see if you still see this issue?

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
