### ISSUE TITLE
UNIQUE constraint failed: ParseObjects.className, ParseObjects.objectId (code 2067)

### ISSUE THREAD

**Issue by hatpick** [parse-community/Parse-SDK-Android#541]
At the beginning, I create about 20 custom objects and using ```pinAll``` I save them into the local datastore in a background service (IntentServic), and then I sync them all to the parse-server (in the same thread) but I hold on to the local objects for offline mode (local data store is enabled and functional). At this point, my app is initialized and ready to go. Let's say a new objects are created on the parse-server on a different device, my device gets notified about it and when I try to fetch and pin these objects (for offlince mode), I get the following errors:
```
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: ParseObjects.className, ParseObjects.objectId (code 2067)
at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1577)
at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1523)
at com.parse.ParseSQLiteDatabase$22.then(ParseSQLiteDatabase.java:318)
at com.parse.ParseSQLiteDatabase$22.then(ParseSQLiteDatabase.java:315)
at bolts.Task$14.run(Task.java:872)
at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
at bolts.Task.completeImmediately(Task.java:863)
at bolts.Task.continueWith(Task.java:661)
at bolts.Task.continueWith(Task.java:672)
at bolts.Task$12.then(Task.java:766)
at bolts.Task$12.then(Task.java:754)
at bolts.Task$15.run(Task.java:917)
```

Any idea what might be the problem? objectId is something internal and I have nothing to do with it, what are some scenarios that this error may happen? @grantland 

Android: 7.0 API 24, Parse SDK: 1.13.1

**Comment by hatpick** [comment]
I constantly get this error, anyone has any ideas why?

**Comment by hatpick** [comment]
I narrowed down this issue to this, if while my background thread is syncing unsaved objects with the cloud or fetching new data from cloud to local objects, I save anything else in my UI thread (or any other background thread for that matter) this issue happens, how can I fix this? seems like it's not thread-safe

**Comment by natario1** [comment]
Would you be able to provide a sample app showing this behavior?

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
