### ISSUE TITLE
re opening #239: crash with custom ParsePushBroadcastReceiver 

### ISSUE THREAD

**Issue by hisham2007** [parse-community/Parse-SDK-Android#552]
Dears,
I face the same issue. I just integrated firebase messaging in the same project that use Parse. crashlytics reported this error but i didn't face it on my own device

**Comment by hisham2007** [comment]
crashlytics:

`Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.RuntimeException: Unable to create application com.tabe3.news.Tabe3NewsApplication: java.lang.IllegalStateException: ParsePlugins is already initialized
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2559)
       at android.app.ActivityThread.access$1700(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1320)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5433)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.RuntimeException: Unable to create application com.tabe3.news.Tabe3NewsApplication: java.lang.IllegalStateException: ParsePlugins is already initialized
       at android.app.LoadedApk.makeApplication(LoadedApk.java:520)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2539)
       at android.app.ActivityThread.access$1700(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1320)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5433)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.IllegalStateException: ParsePlugins is already initialized
       at com.parse.ParsePlugins.set(ParsePlugins.java:39)
       at com.parse.ParsePlugins$Android.initialize(ParsePlugins.java:153)
       at com.parse.Parse.initialize(Parse.java:385)
       at com.tabe3.news.Tabe3NewsApplication.onCreate(Tabe3NewsApplication.java:109)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
       at android.app.LoadedApk.makeApplication(LoadedApk.java:517)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2539)
       at android.app.ActivityThread.access$1700(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1320)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5433)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by Jawnnypoo** [comment]
This is just a warning now and not a crash, so this should not happen for anyone else.
