### ISSUE TITLE
Unable to save ParseUser after failing to save offline

### ISSUE THREAD

**Issue by alexblack** [parse-community/Parse-SDK-Android#574]
Error: `Code 200: bad or missing username`

Parse Android SDK version: 1.13.1
Parse server version: 2.2.23
Repo showing the problem: https://github.com/alexblack/parse-user-test

Repro steps:

1. Turn on airplane mode
2. Init parse, attempt (but fail) to save the user
3. Turn off airplane mode
4. Save the user

Result: "Bad or missing username".  Expected result: user saves.

(Note: if I then restart the app, with airplane mode off, and repeat step 2, the user saves just fine)

Code for step 2:

```
    Parse.initialize(new Parse.Configuration.Builder(this)
      .applicationId(BuildConfig.PARSE_APP_ID)
      .clientKey(BuildConfig.PARSE_CLIENT_KEY)
      .server(BuildConfig.PARSE_URL)
      .build()
    );
    ParseUser.enableAutomaticUser();
    final ParseUser user = ParseUser.getCurrentUser();
    user.saveInBackground().continueWithTask(new Continuation<Void, Task<Void>>() {
      @Override
      public Task<Void> then(Task<Void> task) throws Exception {
        if (task.isFaulted()) Log.e(TAG, "Exception", task.getError());
        return null;
      }
    });
```

Code for step 4:

```
    final ParseUser user = ParseUser.getCurrentUser();
    user.saveInBackground()
```

Stack trace:

```
01-17 15:31:28.032 5226-5226/com.example.test.parseusertest E/MainActivity: Failed to save
com.parse.ParseRequest$ParseRequestException: bad or missing username
at com.parse.ParseRequest.newPermanentException(ParseRequest.java:270)
at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:301)
at com.parse.ParseRESTUserCommand.onResponseAsync(ParseRESTUserCommand.java:126)
at com.parse.ParseRequest$3.then(ParseRequest.java:137)
at com.parse.ParseRequest$3.then(ParseRequest.java:133)
at bolts.Task$15.run(Task.java:917)
at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
at bolts.Task.completeAfterTask(Task.java:908)
at bolts.Task.continueWithTask(Task.java:715)
at bolts.Task.continueWithTask(Task.java:726)
at bolts.Task$13.then(Task.java:818)
at bolts.Task$13.then(Task.java:806)
at bolts.Task$15.run(Task.java:917)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

Logs from parse-server:

```
2017-01-17T23:31:27.929972+00:00 app[web.1]: verbose: REQUEST for [POST] /parse/users: {} method=POST, url=/parse/users, host=removed, connection=close, x-parse-revocable-session=1, x-parse-os-version=6.0, x-parse-app-build-version=1, x-parse-client-key=removed, x-parse-client-version=a1.13.1, x-parse-app-display-version=1.0, x-parse-installation-id=e789df42-c611-4710-accc-250830d6f8c6, user-agent=Parse Android SDK 1.13.1 (com.example.test.parseusertest/1) API Level 23, x-parse-application-id=removed, content-type=application/json, accept-encoding=gzip, x-request-id=bbc0ba4d-9609-450f-9dc4-48cbd114a6a4, x-forwarded-for=69.172.186.177, x-forwarded-proto=http, x-forwarded-port=80, via=1.1 vegur, connect-time=0, x-request-start=1484695887924, total-route-time=0, content-length=2,
2017-01-17T23:31:27.933219+00:00 app[web.1]: error: Error generating response. ParseError { code: 200, message: 'bad or missing username' } code=200, message=bad or missing username
2017-01-17T23:31:28.096502+00:00 app[web.1]: Error: Code 200: bad or missing username
2017-01-17T23:31:28.096505+00:00 app[web.1]:     at /app/index.js:104:11
2017-01-17T23:31:28.096506+00:00 app[web.1]:     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
2017-01-17T23:31:28.096507+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:310:13)
2017-01-17T23:31:28.096508+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:280:7
2017-01-17T23:31:28.096509+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2017-01-17T23:31:28.096510+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2017-01-17T23:31:28.096511+00:00 app[web.1]:     at Immediate.<anonymous> (/app/node_modules/express/lib/application.js:232:9)
2017-01-17T23:31:28.096511+00:00 app[web.1]:     at Immediate.<anonymous> (/app/node_modules/express/lib/router/index.js:618:15)
2017-01-17T23:31:28.096512+00:00 app[web.1]:     at Immediate.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
2017-01-17T23:31:28.096513+00:00 app[web.1]:     at runCallback (timers.js:639:20)
```

Verbose logs from parse-server after restarting the app and trying again from the top with airplane mode off:

```
2017-01-18T00:11:57.949508+00:00 app[web.1]: verbose: REQUEST for [POST] /parse/users: {
2017-01-18T00:11:57.949525+00:00 app[web.1]:   "authData": {
2017-01-18T00:11:57.949526+00:00 app[web.1]:     "anonymous": {
2017-01-18T00:11:57.949527+00:00 app[web.1]:       "id": "dbdb591c-49d6-4eb9-a09a-d500d95b9fb8"
2017-01-18T00:11:57.949528+00:00 app[web.1]:     }
2017-01-18T00:11:57.949529+00:00 app[web.1]:   }
2017-01-18T00:11:57.949531+00:00 app[web.1]: } method=POST, url=/parse/users, host=removed, connection=close, x-parse-os-version=6.0, x-parse-app-build-version=1, x-parse-client-key=removed, x-parse-client-version=a1.13.1, x-parse-app-display-version=1.0, x-parse-installation-id=854d9406-d43b-4c09-b288-8870ba518251, user-agent=Parse Android SDK 1.13.1 (com.example.test.parseusertest/1) API Level 23, x-parse-application-id=removed, content-type=application/json, accept-encoding=gzip, x-request-id=b77ebf42-978a-4329-addd-554abb7e5ade, x-forwarded-for=69.172.186.177, x-forwarded-proto=http, x-forwarded-port=80, via=1.1 vegur, connect-time=0, x-request-start=1484698317931, total-route-time=0, content-length=72, id=dbdb591c-49d6-4eb9-a09a-d500d95b9fb8
2017-01-18T00:11:58.200463+00:00 app[web.1]: verbose: RESPONSE from [POST] /parse/users: {
2017-01-18T00:11:58.200481+00:00 app[web.1]:   "status": 201,
2017-01-18T00:11:58.200482+00:00 app[web.1]:   "response": {
2017-01-18T00:11:58.200483+00:00 app[web.1]:     "objectId": "DCGEgpLTdX",
2017-01-18T00:11:58.200483+00:00 app[web.1]:     "createdAt": "2017-01-18T00:11:57.949Z",
2017-01-18T00:11:58.200484+00:00 app[web.1]:     "username": "QBeGRW4737xpht6kDWwAFQf82",
2017-01-18T00:11:58.200485+00:00 app[web.1]:     "sessionToken": "r:0cab421bfe7108cb23f6fd7f98577aa3"
2017-01-18T00:11:58.200485+00:00 app[web.1]:   },
2017-01-18T00:11:58.200486+00:00 app[web.1]:   "location": "http://host/parse/users/DCGEgpLTdX"
2017-01-18T00:11:58.200488+00:00 app[web.1]: } status=201, objectId=DCGEgpLTdX, createdAt=2017-01-18T00:11:57.949Z, username=QBeGRW4737xpht6kDWwAFQf82, sessionToken=r:0cab421bfe7108cb23f6fd7f98577aa3, location=http://host/parse/users/DCGEgpLTdX
```

**Comment by alexblack** [comment]
The difference between the `save` call that works (after restart) and the one that fails, is that when it works, `ParseObject.operationSetQueue` has one object in it, representing the auth data, and later it has two, that one and an empty one.

After the initial save fails, `ParseObject.operationSetQueue` is modified, with an empty `ParseOperationSet` appended, which means no values are sent to Parse on the next save.

**Comment by alexblack** [comment]
I've worked around this with a hack :(

```
private Task<Void> saveUser(final ParseUser user) {
    return user.saveInBackground().continueWithTask(new Continuation<Void, Task<Void>>() {
      @Override
      public Task<Void> then(Task<Void> task) throws Exception {
        if (task.isFaulted() && task.getError() instanceof ParseException) {
          final ParseException e = (ParseException) task.getError();
          if (e.getCode() == ParseException.USERNAME_MISSING) {
            // try to fix it :)
            fixUser(user);
            return user.saveInBackground();
          } else {
            return Task.forError(task.getError());
          }
        } else {
          return null;
        }
      }
    }, Task.BACKGROUND_EXECUTOR);
  }

  private void fixUser(ParseUser user) throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
    final Method performPut = ParseObject.class.getDeclaredMethod("performPut", String.class, Object.class);
    performPut.setAccessible(true);
    final String AUTH_DATA = "authData";
    performPut.invoke(user, AUTH_DATA, user.get(AUTH_DATA));
  }
```

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
