### ISSUE TITLE
Uploading a File...ParseRequestException

### ISSUE THREAD

**Issue by pcegarra** [parse-community/Parse-SDK-Android#658]
I dont know whats happening.
It was working nice but today the same code is crashing.

When I upload a file "parseFile.saveInBackground" my progressCallback is repeating it selfs 5 or 6 times, then it raise an useless exception:

`W/System.err: com.parse.ParseRequest$ParseRequestException: bad json response
W/System.err:     at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:295)
W/System.err:     at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:308)
W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:142)
 W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:138)
W/System.err:     at bolts.Task$15.run(Task.java:917)
W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
W/System.err:     at bolts.Task.continueWithTask(Task.java:715)
W/System.err:     at bolts.Task.continueWithTask(Task.java:726)
W/System.err:     at bolts.Task$13.then(Task.java:818)
W/System.err:     at bolts.Task$13.then(Task.java:806)
W/System.err:     at bolts.Task$15.run(Task.java:917)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
W/System.err: Caused by: org.json.JSONException: Value <html> of type java.lang.String cannot be converted to JSONObject
 W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:159)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:172)
W/System.err:     at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:298)
W/System.err: 	... 13 more`

Any idea? im getting crazy... on sunday :(

**Comment by pcegarra** [comment]
Ok.. the error was nginx:
https://websistent.com/fix-client-intended-to-send-too-large-body-nginx-error/
