### ISSUE TITLE
com.parse.ParseRequest$ParseRequestException: i/o failure Caused by: java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by jonathan34c** [parse-community/Parse-SDK-Android#691]
Hi I am developing and Android app using parse as back end server with Heroku and Mongo DB. I have looked at the previous case with the same issue, [](https://github.com/parse-community/Parse-SDK-Android/issues/325) I have checked my Mongo db and I am pretty sure I have enough storage.  my parse SDK version is 1.15.8 and I have make sure there's a back slash in my parse server url . I have this problem only when uploading an parse file. Other than that, the server works fine with the SDK. thanks 

`07-11 10:08:50.456 980-980/co.sardines.stats123 W/System.err: com.parse.ParseRequest$ParseRequestException: i/o failure
07-11 10:08:50.457 980-980/co.sardines.stats123 W/System.err:     at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:291)
07-11 10:08:50.457 980-980/co.sardines.stats123 W/System.err:     at com.parse.ParseRequest$2.then(ParseRequest.java:145)
07-11 10:08:50.457 980-980/co.sardines.stats123 W/System.err:     at com.parse.ParseRequest$2.then(ParseRequest.java:139)
07-11 10:08:50.457 980-980/co.sardines.stats123 W/System.err:     at bolts.Task$15.run(Task.java:917)
07-11 10:08:50.457 980-980/co.sardines.stats123 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-11 10:08:50.457 980-980/co.sardines.stats123 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-11 10:08:50.457 980-980/co.sardines.stats123 W/System.err:     at java.lang.Thread.run(Thread.java:761)
07-11 10:08:50.459 980-980/co.sardines.stats123 W/System.err: Caused by: java.net.SocketTimeoutException: timeout
07-11 10:08:50.459 980-980/co.sardines.stats123 W/System.err:     at okio.Okio$4.newTimeoutException(Okio.java:230)
07-11 10:08:50.459 980-980/co.sardines.stats123 W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
07-11 10:08:50.459 980-980/co.sardines.stats123 W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:184)
07-11 10:08:50.459 980-980/co.sardines.stats123 W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
07-11 10:08:50.459 980-980/co.sardines.stats123 W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:41)
07-11 10:08:50.460 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:286)
07-11 10:08:50.460 980-980/co.sardines.stats123 W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
07-11 10:08:50.460 980-980/co.sardines.stats123 W/System.err:     at okio.RealBufferedSink$1.write(RealBufferedSink.java:193)
07-11 10:08:50.460 980-980/co.sardines.stats123 W/System.err:     at java.io.OutputStream.write(OutputStream.java:75)
07-11 10:08:50.460 980-980/co.sardines.stats123 W/System.err:     at com.parse.ParseByteArrayHttpBody.writeTo(ParseByteArrayHttpBody.java:45)
07-11 10:08:50.460 980-980/co.sardines.stats123 W/System.err:     at com.parse.ParseHttpClient$ParseOkHttpRequestBody.writeTo(ParseHttpClient.java:197)
07-11 10:08:50.461 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
07-11 10:08:50.461 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-11 10:08:50.461 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
07-11 10:08:50.461 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-11 10:08:50.461 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-11 10:08:50.461 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
07-11 10:08:50.461 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-11 10:08:50.462 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-11 10:08:50.462 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
07-11 10:08:50.462 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-11 10:08:50.462 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
07-11 10:08:50.462 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-11 10:08:50.462 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-11 10:08:50.463 980-980/co.sardines.stats123 W/System.err:     at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:123)
07-11 10:08:50.463 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-11 10:08:50.463 980-980/co.sardines.stats123 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-11 10:08:50.463 980-980/co.sardines.stats123 W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
07-11 10:08:50.463 980-980/co.sardines.stats123 W/System.err:     at okhttp3.RealCall.execute(RealCall.java:69)
07-11 10:08:50.463 980-980/co.sardines.stats123 W/System.err:     at com.parse.ParseHttpClient.executeInternal(ParseHttpClient.java:84)
07-11 10:08:50.463 980-980/co.sardines.stats123 W/System.err:     at com.parse.ParseHttpClient.execute(ParseHttpClient.java:71)
07-11 10:08:50.463 980-980/co.sardines.stats123 W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:136)
07-11 10:08:50.463 980-980/co.sardines.stats123 W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:133)
07-11 10:08:50.463 980-980/co.sardines.stats123 W/System.err:     at bolts.Task$15.run(Task.java:917)
07-11 10:08:50.464 980-980/co.sardines.stats123 W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
07-11 10:08:50.464 980-980/co.sardines.stats123 W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
07-11 10:08:50.464 980-980/co.sardines.stats123 W/System.err:     at bolts.Task.continueWithTask(Task.java:715)
07-11 10:08:50.464 980-980/co.sardines.stats123 W/System.err:     at bolts.Task.continueWithTask(Task.java:726)
07-11 10:08:50.464 980-980/co.sardines.stats123 W/System.err:     at bolts.Task$13.then(Task.java:818)
07-11 10:08:50.464 980-980/co.sardines.stats123 W/System.err:     at bolts.Task$13.then(Task.java:806)
07-11 10:08:50.464 980-980/co.sardines.stats123 W/System.err: 	... 4 more
07-11 10:08:50.465 980-980/co.sardines.stats123 W/System.err: Caused by: java.net.SocketException: socket is closed
07-11 10:08:50.465 980-980/co.sardines.stats123 W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:818)
07-11 10:08:50.467 980-980/co.sardines.stats123 W/System.err:     at okio.Okio$1.write(Okio.java:79)
07-11 10:08:50.467 980-980/co.sardines.stats123 W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
07-11 10:08:50.467 980-980/co.sardines.stats123 W/System.err: 	... 41 more`

**Comment by Valdezmj** [comment]
Finally my solution!  I am running version 1.16.0 and I still need to use backslash in my server URL.  Can anyone follow up on this and explain why this is an issue?  None of the documentation even hint at this currently.

To clarify for anyone else that stumbles upon this...
Try changing your server URL from
`"https://www.yourserver.com/parse" -> "https:\/\/www.yourserver.com\/parse"`

**Comment by Valdezmj** [comment]
This is still happening on version 1.16.0...

I cannot seem to get Parse any simple queries to work.  When you say you use a backslash in the URL what do you mean?

**Comment by rayyoungnext** [comment]
This happens to me as well. I can see the data saved to the parse server from parse server dashboard. However, the Android client fails to query the data with this error message. I updated from 1.15.8 to 1.16.1 but the same issue is still there.

**Comment by edson-gaspar** [comment]
This was happening with me when I migrated to a new ubuntu with nginx with ssl protocols.
I changed to support old TLS and the problem was solved.
-change on nginx ssl protocols to:
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
-restart nginx.
All done.

**Comment by Shamsudeen12** [comment]
Hello, I keep on getting i/o faliure anytime I run my application, please help

**Comment by Shamsudeen12** [comment]
Every single time, and I have good connection

**Comment by akshay-kochhar** [comment]
I am facing similar issue and getting i/o failure. I am able to verify the curl request

**Comment by Shamsudeen12** [comment]
It happens when you are using an android 9 or 10 device to test. What you have to do is add this setting to your mainfest.xml

android:usesClearTextTraffic="true"
