### ISSUE TITLE
unable to initialize after server update to version 2.5.3

### ISSUE THREAD

**Issue by kyle8615** [parse-community/Parse-SDK-Android#693]
After I update the Parse Server version from 2.2.16 to 2.5.3, I am unable to use my Android device to initialize. is there some things wrong?

there is my eror log below: 

`07-26 23:38:54.084 7879-7925/? I/ParseLogInterceptor: Type : Request
07-26 23:38:54.084 7879-7925/? I/ParseLogInterceptor: Request-Id : 0
07-26 23:38:54.084 7879-7925/? I/ParseLogInterceptor: Url : https://xxxxxxxxxxxxxxxxx:3002/sx/parse/classes/_Installation
07-26 23:38:54.084 7879-7925/? I/ParseLogInterceptor: Method : POST
07-26 23:38:54.084 7879-7925/? I/ParseLogInterceptor: Headers : {x-parse-app-build-version=53, x-parse-app-display-version=3.0.8.sx, host=xxxxxxxxxxxxxxxx:3002, content-type=application/json, user-agent=Parse Android SDK 1.14.1 (xxxxxxxxxxxx/53) API Level 24, connection=Keep-Alive, accept-encoding=gzip, Content-Type=application/json, x-parse-os-version=7.0, x-parse-client-key=AdpH5YLiJ20QQS0UE0IMeFBh85g4JtUWN3LkDYCG, content-length=289, x-parse-client-version=a1.14.1, Content-Length=289, x-parse-installation-id=72f8474f-9855-4940-9072-3004d0352f62, x-parse-application-id=jbaewKt1oKdIKFrd2jLj6gxDqewdbEf8ZNeptws6}
07-26 23:38:54.084 7879-7925/? I/ParseLogInterceptor: Body : {
                                                          "pushType": "gcm",
                                                          "localeIdentifier": "zh-TW",
                                                          "appVersion": "3.0.8.sx",
                                                          "deviceType": "android",
                                                          "uniqueId": "73578762728491d1",
                                                          "appIdentifier": "xxxxxxxxxxxxxx",
                                                          "installationId": "xxxxxxxxxxxxxx",
                                                          "parseVersion": "1.14.1",
                                                          "appName": "xxxxxxxxxx",
                                                          "timeZone": "Asia\/Taipei"
                                                      }
07-26 23:38:54.085 7879-7925/? I/ParseLogInterceptor: --------------`

`07-26 23:38:54.195 7879-7925/? I/ParseLogInterceptor: Type : Response
07-26 23:38:54.195 7879-7925/? I/ParseLogInterceptor: Request-Id : 0
07-26 23:38:54.195 7879-7925/? I/ParseLogInterceptor: Status-Code : 403
07-26 23:38:54.195 7879-7925/? I/ParseLogInterceptor: Reason-Phrase : 
07-26 23:38:54.195 7879-7925/? I/ParseLogInterceptor: Headers : {access-control-allow-headers=X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, Content-Type, server=nginx/1.4.6 (Ubuntu), date=Wed, 26 Jul 2017 15:38:53 GMT, access-control-allow-methods=GET,PUT,POST,DELETE,OPTIONS, content-length=24, x-powered-by=Express, access-control-allow-origin=*}
07-26 23:38:54.195 7879-7925/? I/ParseLogInterceptor: Body : Ignored
07-26 23:38:54.195 7879-7925/? I/ParseLogInterceptor: --------------`

`07-26 23:38:54.632 7879-7879/com.jaybo.avengers.sx E/ParseUtility: initialize
                                                                   com.parse.ParseRequest$ParseRequestException: unauthorized
                                                                       at com.parse.ParseRequest.newPermanentException(ParseRequest.java:270)
                                                                       at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:301)
                                                                       at com.parse.ParseRequest$3.then(ParseRequest.java:137)
                                                                       at com.parse.ParseRequest$3.then(ParseRequest.java:133)
                                                                       at a.j$6.run(Task.java:917)
                                                                       at a.c$a.execute(BoltsExecutors.java:105)
                                                                       at a.j.d(Task.java:908)
                                                                       at a.j.b(Task.java:715)
                                                                       at a.j.b(Task.java:726)
                                                                       at a.j$4.a(Task.java:818)
                                                                       at a.j$4.then(Task.java:806)
                                                                       at a.j$6.run(Task.java:917)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                       at java.lang.Thread.run(Thread.java:761)`

**Comment by addisonElliott** [comment]
You posted this issue a few weeks ago but it looks like the exception you are getting is "unauthorized". 

This typically means the Parse Server is rejecting the client connection for some reason. When this occurred to me, it was due to an invalid client key. I would suggest replacing your application ID, client key, and server address.

**Comment by Jawnnypoo** [comment]
Thanks @addisonElliott That should be the right fix
