### ISSUE TITLE
java.lang.IllegalAccessError: Method 'void bolts.Task.<init>()' is inaccessible to class 'bolts.TaskCompletionSource'

### ISSUE THREAD

**Issue by IvanKlipok** [parse-community/Parse-SDK-Android#701]
java.lang.IllegalAccessError: Method 'void bolts.Task.<init>()' is inaccessible to class 'bolts.TaskCompletionSource' (declaration of 'bolts.TaskCompletionSource' appears in /data/app/com.steaklocker.steaklocker-1/base.apk:classes10.dex)
                                                                               at bolts.TaskCompletionSource.<init>(TaskCompletionSource.java:18)
                                                                               at com.parse.ParseTaskUtils.callbackOnMainThreadAsync(ParseTaskUtils.java:100)
                                                                               at com.parse.ParseTaskUtils.callbackOnMainThreadAsync(ParseTaskUtils.java:72)
                                                                               at com.parse.ParseTaskUtils.callbackOnMainThreadAsync(ParseTaskUtils.java:59)
                                                                               at com.parse.ParsePush.subscribeInBackground(ParsePush.java:264)

**Comment by Jawnnypoo** [comment]
Are you using Multidex?

**Comment by IvanKlipok** [comment]
Yes

**Comment by Jawnnypoo** [comment]
Sounds like your setup is incorrect there then. Be sure to follow the guide fully. https://developer.android.com/studio/build/multidex.html
