### ISSUE TITLE
Unable to start service com.parse.PushService in devices with version < 8.0

### ISSUE THREAD

**Issue by FcoCGN** [parse-community/Parse-SDK-Android#762]
I have received this error since I upgraded to version 1.16.3 but on devices with versions less than Oreo:

Fatal Exception: java.lang.RuntimeException: Unable to start service com.parse.PushService@37d082b with Intent { act=com.google.android.c2dm.intent.REGISTRATION flg=0x10 pkg=com.package.example cmp=com.package.example/com.parse.PushService (has extras) }: java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.concurrent.ExecutorService.execute(java.lang.Runnable)' on a null object reference
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2951)
at android.app.ActivityThread.access$2100(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5348)
at java.lang.reflect.Method.invoke(Method.java)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.concurrent.ExecutorService.execute(java.lang.Runnable)' on a null object reference
at com.parse.PushService.onStartCommand(PushService.java:239)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2934)
at android.app.ActivityThread.access$2100(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5348)
at java.lang.reflect.Method.invoke(Method.java)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

**Comment by natario1** [comment]
That's boring. Maybe it's better to make it static.

**Comment by FcoCGN** [comment]
Ok, I've been doing tests and I think the error was caused by performing Parse.initialize() on a thread.

I had to create it in a thread because the app caused ANR in the getCurrentInstallation() method when calling ParseTaskUtils.wait() in some devices.

**Comment by adybuciuman** [comment]
With the latest version (1.16.3) works great on all API's, except Android 4.4
