### ISSUE TITLE
Parse Notification issues when initializing Parse in a later stage (Multi-app awareness)

### ISSUE THREAD

**Issue by pargu** [parse-community/Parse-SDK-Android#771]
This might not be an issue per se, but would really like som feedback on the matter, if someone has a fix for this.

So we are setting up a new server and need to initialize different Parse Server instances upon login. The server is all setup using PM2 with different setups, but the app has some issues when initializing Parse on the Android side.

Previously when we only had one instance we initialized Parse in the Application class, as per documentation. But now we initialize the correct server upon user login. Everything works good with this system except Push Notifications getting crashes on some older devices on first installation, and on devices after rebooting them. This last part happens when there are some in queue on startup and for new pushes that are sent afterwards.

The strange thing is that it works on most devices for the first installation. The logical thing would be that they all should fail? 

This is the crash log for the issue

1.15.8 
`
java.lang.RuntimeException: Unable to create service com.parse.PushService: java.lang.NullPointerException
                                                                           at android.app.ActivityThread.handleCreateService(ActivityThread.java:2779)
                                                                           at android.app.ActivityThread.access$1800(ActivityThread.java:151)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                           at android.os.Looper.loop(Looper.java:193)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5332)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.NullPointerException
                                                                           at com.parse.PushService.onCreate(PushService.java:230)
                                                                           at android.app.ActivityThread.handleCreateService(ActivityThread.java:2769)`
1.16.3
`java.lang.RuntimeException: Unable to start service com.parse.PushService@XXXXX with Intent { act=com.google.android.c2dm.intent.REGISTRATION flg=0x10 pkg=xxxxxxx cmp=xxxxxxx/com.parse.PushService (has extras) }: java.lang.NullPointerException
                                                                           at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2923)
                                                                           at android.app.ActivityThread.access$2100(ActivityThread.java:151)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1439)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                           at android.os.Looper.loop(Looper.java:193)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5332)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.NullPointerException
                                                                           at com.parse.Parse.checkContext(Parse.java:624)
                                                                           at com.parse.Parse.getApplicationContext(Parse.java:461)
                                                                           at com.parse.ManifestInfo.getContext(ManifestInfo.java:219)
                                                                           at com.parse.ManifestInfo.getIntentReceivers(ManifestInfo.java:136)
                                                                           at com.parse.ManifestInfo.hasIntentReceiver(ManifestInfo.java:128)
                                                                           at com.parse.ParsePushBroadcastReceiver.isSupported(ParsePushBroadcastReceiver.java:116)
                                                                           at com.parse.ManifestInfo.findPushType(ManifestInfo.java:179)
                                                                           at com.parse.ManifestInfo.getPushType(ManifestInfo.java:170)
                                                                           at com.parse.PushService.onStartCommand(PushService.java:235)
                                                                           at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2906)`

Is there a workaround for this where it is possible to setup push later when initializing Parse and not have the com.parse.PushService in Manifest? Or are we stuck with one server solution until multi-app is supported in the Parse platform?

**Comment by natario1** [comment]
For push to work you should still initialize in the application class, maybe with an if clause in your case. If the server is sending pushes you probably know which server to connect at that point.

**Comment by pargu** [comment]
Thank you for the quick response natario1. 

Well the issue is we don't know which server the user should be connected to until the user is registered or logged in. It will be the same build that they download from Google Play, so in the Application class we don't know what to initialize. 

We can't either force it to be country-based as they could live in one but have business in the other country. So the connection is made through their registration, where we can point them to correct organization and on to the right server. So that makes it a bit tricky.

Any suggestions?

**Comment by natario1** [comment]
I am assuming that if the device is receiving push from server X, it means the user has previously logged in, was assigned X and is persisting. In this case you could store X in the device on login and use that in the Application class later

**Comment by pargu** [comment]
Thank you for your response.

Yes, this would work after the user is pointed to the server, but on the first installation / first time they download and opened the app, sadly the issue still remains. Or I might misinterpret what you mean? Could look on region on device, but will not be a 100 percent working solution, as stated above.

**Comment by pargu** [comment]
Hi natario1,
Iv'e tried to come up with some solutions these past days to get around this, but I'm left empty handed unfortunately. I can see that you have been contributing to these classes, so before I go into looking at them myself, in more depth, to find a solution for a local hack, it would be good to know if you think this would even be possible? Or is it to integrated with GCM/FCM, that it needs to be initialized in Manifest?

**Comment by natario1** [comment]
Yes you would have the issue on first installation. But that was just my idea. Regarding the hack, I don't really know if it's possible, I wouldn't like to try.

**Comment by pargu** [comment]
Ok, thank you for responding. We'll try to find another solution for the setup 👍
