### ISSUE TITLE
Failed resolving Lcom/parse/ParsePlugins$1; interface 4200 'Lokhttp3/Interceptor;'

### ISSUE THREAD

**Issue by damain** [parse-community/Parse-SDK-Android#779]
I just tried installing the parse SDK on android studio 3.0.1 and got the following errors in Logcat.  Help please. As soon as I navigate to the page that the parse code is in the app crashes

01-30 12:39:48.698 2833-2833/kav.ej I/dalvikvm: Failed resolving Lcom/parse/ParsePlugins$1; interface 4200 'Lokhttp3/Interceptor;'
01-30 12:39:48.698 2833-2833/kav.ej W/dalvikvm: Link of class 'Lcom/parse/ParsePlugins$1;' failed
01-30 12:39:48.698 2833-2833/kav.ej E/dalvikvm: Could not find class 'okhttp3.OkHttpClient$Builder', referenced from method com.parse.ParsePlugins.restClient
01-30 12:39:48.698 2833-2833/kav.ej W/dalvikvm: VFY: unable to resolve new-instance 4202 (Lokhttp3/OkHttpClient$Builder;) in Lcom/parse/ParsePlugins;
...
then this fatal error

FATAL EXCEPTION: pool-1-thread-1
                                                      Process: kav.ej, PID: 2833
                                                      java.lang.NoClassDefFoundError: okhttp3.OkHttpClient$Builder
                                                          at com.parse.ParsePlugins.restClient(ParsePlugins.java:96)
                                                          at com.parse.Parse.getEventuallyQueue(Parse.java:594)
                                                          at com.parse.Parse.access$800(Parse.java:36)
                                                          at com.parse.Parse$1.call(Parse.java:400)
                                                          at com.parse.Parse$1.call(Parse.java:397)
                                                          at bolts.Task$4.run(Task.java:357)
                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                          at java.lang.Thread.run(Thread.java:841)

**Comment by rogerhu** [comment]
I suspect you need to add okhttp as a dependency -- there is a Gradle bug we're trying to fix:

https://github.com/parse-community/Parse-SDK-Android/issues/773

**Comment by damain** [comment]
I am very new to Android development I know it goes in the app.gradle but what would that line look like

**Comment by damain** [comment]
i added 
implementation 'com.squareup.okhttp3:okhttp:3.9.1'

**Comment by Jawnnypoo** [comment]
Yep, that should be it.
