### ISSUE TITLE
Push received on ICS (4.0.4) crashes app

### ISSUE THREAD

**Issue by adammlevy** [parse-community/Parse-SDK-Android#792]
I am getting the following crash right after receiving a push on my Android phone running ICS. 
Note that I do not have this problem on an emulator running 8.0.  

` FATAL EXCEPTION: main
                                                                     java.lang.StackOverflowError
                                                                         at java.lang.Class.getClassLoaderImpl(Class.java:395)
                                                                         at java.lang.Class.getClassLoader(Class.java:376)
                                                                         at android.os.Bundle.<init>(Bundle.java:69)
                                                                         at android.app.Notification.<init>(Notification.java:282)
                                                                         at com.parse.NotificationCompat$Builder.<init>(NotificationCompat.java:133)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:61)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                         at com.parse.NotificationCompat$Builder.build(NotificationCompat.java:338)
                                                                         at com.parse.NotificationCompat$NotificationCompatImplBase.build(NotificationCompat.java:69)
                                                                     	at com.parse.NotificationCompat$Builder.build(Notificati`

Setting a breakpoint reveals that the following method is getting recursively called 

```static class NotificationCompatImplBase implements  NotificationCompatImpl {
    @Override
    public Notification build(Builder builder) {
      Notification result = builder.mNotification;
      NotificationCompat.Builder newBuilder = new NotificationCompat.Builder(builder.mContext);
      newBuilder.setContentTitle(builder.mContentTitle);
      newBuilder.setContentText(builder.mContentText);
      newBuilder.setContentIntent(builder.mContentIntent);
      // translate high priority requests into legacy flag
      if (builder.mPriority > PRIORITY_DEFAULT) {
        result.flags |= FLAG_HIGH_PRIORITY;
      }
      // this calls current method recursively 
      return newBuilder.build();
    }
  }

**Comment by Jawnnypoo** [comment]
@adammlevy This should be fixed with 1.17.3
