### ISSUE TITLE
Attempted to find non-existent uuid

### ISSUE THREAD

**Issue by olheimer** [parse-community/Parse-SDK-Android#806]
I'm using the local data store. Somehow after a while using my App I do get an IllegalStateException:

java.lang.IllegalStateException: Attempted to find non-existent uuid 2a5d65bb-29e1-4e8a-bcf9-b8ca1ec2d653
        at com.parse.OfflineStore$3.then(OfflineStore.java:270)
        at com.parse.OfflineStore$3.then(OfflineStore.java:263)
        at bolts.Task$14.run(Task.java:872)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeImmediately(Task.java:863)
        at bolts.Task.continueWith(Task.java:661)
        at bolts.Task.continueWith(Task.java:672)
        at bolts.Task$12.then(Task.java:766)
        at bolts.Task$12.then(Task.java:754)
        at bolts.Task$15.run(Task.java:917)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeAfterTask(Task.java:908)
        at bolts.Task.access$100(Task.java:32)
        at bolts.Task$11.then(Task.java:708)
        at bolts.Task$11.then(Task.java:705)
        at bolts.Task.runContinuations(Task.java:956)
        at bolts.Task.trySetResult(Task.java:994)
        at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
        at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
        at bolts.Task$15$1.then(Task.java:934)
        at bolts.Task$15$1.then(Task.java:921)
        at bolts.Task$14.run(Task.java:872)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeImmediately(Task.java:863)
        at bolts.Task.continueWith(Task.java:661)
        at bolts.Task.continueWith(Task.java:672)
        at bolts.Task$15.run(Task.java:921)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

From this point on the only option is to delete data/uninstall the app. Otherwise app is crashing with the same error on and on.

I'm using Parse 1.16.7
The issue happens at least on Android 8 and Android 6.

I saw that the same bug exists for iOS and should have been fixed with 1.17 release.

Is there any action on this under Android?

**Comment by olheimer** [comment]
Ist there any idea how to fix this?

**Comment by flovilmart** [comment]
Do you have any steps to reproduce this issue?
