### ISSUE TITLE
1.17.3: Unable to instantiate receiver com.parse.GcmBroadcastReceiver

### ISSUE THREAD

**Issue by lxknvlk** [parse-community/Parse-SDK-Android#844]
Upgrading sdk version from 1.16.7 to 1.17.3, now this happens when my device receives a push message:

	java.lang.RuntimeException: Unable to instantiate receiver com.parse.GcmBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "com.parse.GcmBroadcastReceiver" on path: DexPathList[[zip file "/data/app/myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/myapp-1/lib/arm, /data/app/myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, system/vendor/lib, system/vendor/lib/egl, system/lib/hw]]
	   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2812)
	   at android.app.ActivityThread.access$1800(ActivityThread.java:150)
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489)
	   at android.os.Handler.dispatchMessage(Handler.java:102)
	   at android.os.Looper.loop(Looper.java:168)
	   at android.app.ActivityThread.main(ActivityThread.java:5885)
	   at java.lang.reflect.Method.invoke(Native Method)
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
	Caused by: java.lang.ClassNotFoundException: Didn't find class "com.parse.GcmBroadcastReceiver" on path: DexPathList[[zip file "/data/app/myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/myapp-1/lib/arm, /data/app/myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, system/vendor/lib, system/vendor/lib/egl, system/lib/hw]]
	   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2807)
	   at android.app.ActivityThread.access$1800(ActivityThread.java:150) 
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489) 
	   at android.os.Handler.dispatchMessage(Handler.java:102) 
	   at android.os.Looper.loop(Looper.java:168) 
	   at android.app.ActivityThread.main(ActivityThread.java:5885) 
	   at java.lang.reflect.Method.invoke(Native Method) 
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
	Suppressed: java.lang.ClassNotFoundException: com.parse.GcmBroadcastReceiver
	   at java.lang.Class.classForName(Native Method)
	   at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
	   at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
	   at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
			... 10 more

Rolling back to 1.16.7 everything works ok.

I have this in my manifest:

	<receiver
		android:name="com.parse.GcmBroadcastReceiver"
		android:permission="com.google.android.c2dm.permission.SEND">
		<intent-filter>
			<action android:name="com.google.android.c2dm.intent.RECEIVE" />
			<action android:name="com.google.android.c2dm.intent.REGISTRATION" />

			<category android:name="${applicationId}" />
		</intent-filter>
	</receiver>

**Comment by pparreno** [comment]
Same here, been receiving it since the upgrade.

**Comment by pcegarra** [comment]
Ops, same error

**Comment by flovilmart** [comment]
Did you all check the migration to fcm? https://github.com/parse-community/Parse-SDK-Android/blob/master/README.md

There’s a step that involve removing GcmBroadcastReceiver and I believe this is your issue. @rogerhu, can it be?

**Comment by Jawnnypoo** [comment]
Yep,  this is an error due to the SDK changing and no longer including GCM support by default. You can either migrate to [FCM](https://github.com/parse-community/Parse-SDK-Android/tree/master/fcm) or use the deprecated [GCM](https://github.com/parse-community/Parse-SDK-Android/tree/master/gcm) package

**Comment by lxknvlk** [comment]
@Jawnnypoo my project uses GCM, i followed your link to the GCM page, done everything like that and this error still occurs. I even configured proguard with -keep class com.parse.**. I am using multidex.1.0.3 in case that can shed some light. 

I have a huge project with a lot of users, i think i should update parse version. Are there any other solutions?
