### ISSUE TITLE
 Method requires Local Datastore. Please refer to `Parse#enableLocalDatastore(Context)`.

### ISSUE THREAD

**Issue by Likeyong** [parse-community/Parse-SDK-Android#851]
My Application:

```
 Parse.enableLocalDatastore(this);
        Parse.initialize(new Parse.Configuration.Builder(this)
                .applicationId("*****app")
//                .clientKey("YOUR_CLIENT_KEY")
                .server("https://*****/")
                .build()
```

**but when i  do it  :**

```
ParseQuery<ParseObject> query = ParseQuery.getQuery(FILE_RECEIVE);
        query.findInBackground(new FindCallback<ParseObject>() {
            @Override
            public void done(List<ParseObject> objects, ParseException e) {
                if (e == null) {

                    ParseObject.pinAllInBackground(objects, new SaveCallback() {
                        @Override
                        public void done(ParseException e) {
                            callback.onSuccess();
                        }
                    });
                }
            }
        });
```

i got it  
` java.lang.IllegalStateException: Method requires Local Datastore. Please refer to `Parse#enableLocalDatastore(Context)`.
                      at com.parse.ParseObject.pinAllInBackground(ParseObject.java:3717)
                      at com.parse.ParseObject.pinAllInBackground(ParseObject.java:3711)
                      at com.parse.ParseObject.pinAllInBackground(ParseObject.java:3816)`

**Comment by Likeyong** [comment]
I solved the problem like this.

```
 Parse.enableLocalDatastore(this);
        Parse.initialize(new Parse.Configuration.Builder(this)
                .applicationId("*****app")
//                .clientKey("YOUR_CLIENT_KEY")
                .server("https://*****/")
               .enableLocalDataStore()
                .build()
```

**Comment by Jawnnypoo** [comment]
Glad you were able to resolve it!
