### ISSUE TITLE
Unable to save parse file... Getting bad json exception

### ISSUE THREAD

**Issue by MustanserIqbal93** [parse-community/Parse-SDK-Android#876]
Hi i am trying to save the parse file. while uploading it give me 100% progress but after it end up with bad json exception.
below is the code which i am using to upload the file.

          final IncidentContent incidentContent = new IncidentContent();
            incidentContent.setType(contentDb.typeOfMedia);
            if (contentDb.typeOfMedia.equals(VIDEO_CONTENT)) {
                incidentContent.setThumbnail(new ParseFile(new File(contentDb.thumbnailPath)));
            }
            incidentContent.setLocalContent(false);
            final ParseFile file = new ParseFile(new File(contentDb.imagePath));
            file.saveInBackground(new ProgressCallback() {
                @Override
                public void done(Integer percentDone) {
                    incidentDb.itemProgress = percentDone;
                    incidentDb.update();
                    if (percentDone == 100 || percentDone > 100) {
                            incidentContent.setMedia(file);
                            if (contentDb.typeOfMedia.equals(VIDEO_CONTENT)) {

                                incidentContent.getThumbnail().saveInBackground(new ProgressCallback() {
                                    @Override
                                    public void done(Integer percentDone) {
                                        if (percentDone == 100 || percentDone > 100) {
                                             incidentContent.saveInBackground(); contentDb);
                                        }
                                    }
                                });

                            } else {
                                incidentContent.saveInBackground();
                            }
                    }
                    // send broadcast here
                    sendBroadCastToUser();
                }
            });

**Here is full stack trace.**

08-18 01:49:37.070 8031-8031/? W/System.err: com.parse.ParseRequest$ParseRequestException: bad json response
08-18 01:49:37.071 8031-8031/? W/System.err:     at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:292)
08-18 01:49:37.071 8031-8031/? W/System.err:     at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:303)
08-18 01:49:37.071 8031-8031/? W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:138)
08-18 01:49:37.071 8031-8031/? W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:134)
08-18 01:49:37.071 8031-8031/? W/System.err:     at bolts.Task$15.run(Task.java:917)
08-18 01:49:37.071 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.071 8031-8031/? W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
08-18 01:49:37.071 8031-8031/? W/System.err:     at bolts.Task.continueWithTask(Task.java:715)
08-18 01:49:37.071 8031-8031/? W/System.err:     at bolts.Task.continueWithTask(Task.java:726)
08-18 01:49:37.071 8031-8031/? W/System.err:     at bolts.Task$13.then(Task.java:818)
08-18 01:49:37.072 8031-8031/? W/System.err:     at bolts.Task$13.then(Task.java:806)
08-18 01:49:37.072 8031-8031/? W/System.err:     at bolts.Task$15.run(Task.java:917)
08-18 01:49:37.072 8031-8031/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-18 01:49:37.072 8031-8031/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-18 01:49:37.072 8031-8031/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
08-18 01:49:37.072 8031-8031/? W/System.err: Caused by: org.json.JSONException: Value <html> of type java.lang.String cannot be converted to JSONObject
08-18 01:49:37.073 8031-8031/? W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
08-18 01:49:37.073 8031-8031/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
08-18 01:49:37.073 8031-8031/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
08-18 01:49:37.073 8031-8031/? W/System.err:     at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:293)
08-18 01:49:37.073 8031-8031/? W/System.err: 	... 13 more
08-18 01:49:37.073 8031-8031/? W/System.err: com.parse.ParseException: java.lang.IllegalStateException: Unable to encode an unsaved ParseFile.
08-18 01:49:37.074 8031-8031/? W/System.err:     at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:114)
08-18 01:49:37.074 8031-8031/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
08-18 01:49:37.074 8031-8031/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
08-18 01:49:37.074 8031-8031/? W/System.err:     at android.os.Looper.loop(Looper.java:207)
08-18 01:49:37.074 8031-8031/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5728)
08-18 01:49:37.074 8031-8031/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-18 01:49:37.074 8031-8031/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
08-18 01:49:37.075 8031-8031/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
08-18 01:49:37.075 8031-8031/? W/System.err: Caused by: java.lang.IllegalStateException: Unable to encode an unsaved ParseFile.
08-18 01:49:37.076 8031-8031/? W/System.err:     at com.parse.ParseFile.encode(ParseFile.java:733)
08-18 01:49:37.076 8031-8031/? W/System.err:     at com.parse.ParseEncoder.encode(ParseEncoder.java:76)
08-18 01:49:37.076 8031-8031/? W/System.err:     at com.parse.ParseSetOperation.encode(ParseSetOperation.java:32)
08-18 01:49:37.077 8031-8031/? W/System.err:     at com.parse.ParseEncoder.encode(ParseEncoder.java:125)
08-18 01:49:37.077 8031-8031/? W/System.err:     at com.parse.ParseObjectCoder.encode(ParseObjectCoder.java:60)
08-18 01:49:37.077 8031-8031/? W/System.err:     at com.parse.NetworkObjectController.saveAsync(NetworkObjectController.java:60)
08-18 01:49:37.077 8031-8031/? W/System.err:     at com.parse.ParseObject$13.then(ParseObject.java:1608)
08-18 01:49:37.078 8031-8031/? W/System.err:     at com.parse.ParseObject$13.then(ParseObject.java:1603)
08-18 01:49:37.078 8031-8031/? W/System.err:     at bolts.Task$15.run(Task.java:917)
08-18 01:49:37.078 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.078 8031-8031/? W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
08-18 01:49:37.078 8031-8031/? W/System.err:     at bolts.Task.continueWithTask(Task.java:715)
08-18 01:49:37.078 8031-8031/? W/System.err:     at bolts.Task.continueWithTask(Task.java:726)
08-18 01:49:37.078 8031-8031/? W/System.err:     at bolts.Task$13.then(Task.java:818)
08-18 01:49:37.078 8031-8031/? W/System.err:     at bolts.Task$13.then(Task.java:806)
08-18 01:49:37.078 8031-8031/? W/System.err:     at bolts.Task$15.run(Task.java:917)
08-18 01:49:37.079 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.079 8031-8031/? W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
08-18 01:49:37.079 8031-8031/? W/System.err:     at bolts.Task.access$100(Task.java:32)
08-18 01:49:37.079 8031-8031/? W/System.err:     at bolts.Task$11.then(Task.java:708)
08-18 01:49:37.079 8031-8031/? W/System.err:     at bolts.Task$11.then(Task.java:705)
08-18 01:49:37.079 8031-8031/? W/System.err:     at bolts.Task.runContinuations(Task.java:956)
08-18 01:49:37.079 8031-8031/? W/System.err:     at bolts.Task.trySetResult(Task.java:994)
08-18 01:49:37.079 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
08-18 01:49:37.079 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
08-18 01:49:37.079 8031-8031/? W/System.err:     at bolts.Task$15$1.then(Task.java:934)
08-18 01:49:37.079 8031-8031/? W/System.err:     at bolts.Task$15$1.then(Task.java:921)
08-18 01:49:37.081 8031-8031/? W/System.err:     at bolts.Task$14.run(Task.java:872)
08-18 01:49:37.081 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.081 8031-8031/? W/System.err:     at bolts.Task.completeImmediately(Task.java:863)
08-18 01:49:37.081 8031-8031/? W/System.err:     at bolts.Task.continueWith(Task.java:661)
08-18 01:49:37.081 8031-8031/? W/System.err:     at bolts.Task.continueWith(Task.java:672)
08-18 01:49:37.081 8031-8031/? W/System.err:     at bolts.Task$15.run(Task.java:921)
08-18 01:49:37.082 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.082 8031-8031/? W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
08-18 01:49:37.082 8031-8031/? W/System.err:     at bolts.Task.access$100(Task.java:32)
08-18 01:49:37.082 8031-8031/? W/System.err:     at bolts.Task$11.then(Task.java:708)
08-18 01:49:37.082 8031-8031/? W/System.err:     at bolts.Task$11.then(Task.java:705)
08-18 01:49:37.082 8031-8031/? W/System.err:     at bolts.Task.runContinuations(Task.java:956)
08-18 01:49:37.082 8031-8031/? W/System.err:     at bolts.Task.trySetResult(Task.java:994)
08-18 01:49:37.082 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
08-18 01:49:37.082 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
08-18 01:49:37.082 8031-8031/? W/System.err:     at bolts.Task$8.then(Task.java:564)
08-18 01:49:37.082 8031-8031/? W/System.err:     at bolts.Task$8.then(Task.java:538)
08-18 01:49:37.083 8031-8031/? W/System.err:     at bolts.Task$14.run(Task.java:872)
08-18 01:49:37.083 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.083 8031-8031/? W/System.err:     at bolts.Task.completeImmediately(Task.java:863)
08-18 01:49:37.083 8031-8031/? W/System.err:     at bolts.Task.access$000(Task.java:32)
08-18 01:49:37.083 8031-8031/? W/System.err:     at bolts.Task$10.then(Task.java:654)
08-18 01:49:37.083 8031-8031/? W/System.err:     at bolts.Task$10.then(Task.java:651)
08-18 01:49:37.083 8031-8031/? W/System.err:     at bolts.Task.runContinuations(Task.java:956)
08-18 01:49:37.084 8031-8031/? W/System.err:     at bolts.Task.trySetResult(Task.java:994)
08-18 01:49:37.084 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
08-18 01:49:37.084 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
08-18 01:49:37.084 8031-8031/? W/System.err:     at bolts.Task$14.run(Task.java:873)
08-18 01:49:37.084 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.Task.completeImmediately(Task.java:863)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.Task.access$000(Task.java:32)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.Task$10.then(Task.java:654)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.Task$10.then(Task.java:651)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.Task.runContinuations(Task.java:956)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.Task.trySetError(Task.java:1011)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.Task$8.then(Task.java:554)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.Task$8.then(Task.java:538)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.Task$14.run(Task.java:872)
08-18 01:49:37.085 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.Task.completeImmediately(Task.java:863)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.Task.access$000(Task.java:32)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.Task$10.then(Task.java:654)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.Task$10.then(Task.java:651)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.Task.runContinuations(Task.java:956)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.Task.trySetError(Task.java:1011)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.Task$15$1.then(Task.java:932)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.Task$15$1.then(Task.java:921)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.Task$14.run(Task.java:872)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.086 8031-8031/? W/System.err:     at bolts.Task.completeImmediately(Task.java:863)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.Task.access$000(Task.java:32)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.Task$10.then(Task.java:654)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.Task$10.then(Task.java:651)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.Task.runContinuations(Task.java:956)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.Task.trySetError(Task.java:1011)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.Task$15$1.then(Task.java:932)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.Task$15$1.then(Task.java:921)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.Task$14.run(Task.java:872)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.Task.completeImmediately(Task.java:863)
08-18 01:49:37.087 8031-8031/? W/System.err:     at bolts.Task.continueWith(Task.java:661)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.Task.continueWith(Task.java:672)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.Task$15.run(Task.java:921)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.Task.access$100(Task.java:32)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.Task$11.then(Task.java:708)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.Task$11.then(Task.java:705)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.Task.runContinuations(Task.java:956)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.Task.trySetError(Task.java:1011)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.trySetError(TaskCompletionSource.java:46)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.TaskCompletionSource.setError(TaskCompletionSource.java:71)
08-18 01:49:37.088 8031-8031/? W/System.err:     at bolts.Task$15$1.then(Task.java:932)
08-18 01:49:37.089 8031-8031/? W/System.err:     at bolts.Task$15$1.then(Task.java:921)
08-18 01:49:37.089 8031-8031/? W/System.err:     at bolts.Task$14.run(Task.java:872)
08-18 01:49:37.089 8031-8031/? W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
08-18 01:49:37.089 8031-8031/? W/System.err:     at bolts.Task.completeImmediately(Task.java:863)
08-18 01:49:37.089 8031-8031/? W/System.err:     at bolts.Task.continueWith(Task.java:661)
08-18 01:49:37.089 8031-8031/? W/System.err:     at bolts.Task.continueWith(Task.java:672)
08-18 01:49:37.089 8031-8031/? W/System.err:     at bolts.Task$15.run(Task.java:921)
08-18 01:49:37.089 8031-8031/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-18 01:49:37.089 8031-8031/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-18 01:49:37.089 8031-8031/? W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by AlejandroHCruz** [comment]
I've seen this error too

**Comment by grantespo** [comment]
PublicServerURL should be set as https, not http in index.js
