### ISSUE TITLE
Parse notification not working with Android 9

### ISSUE THREAD

**Issue by matdev** [parse-community/Parse-SDK-Android#886]
After completing a Parse installation for a new user of our app, the device token in our Parse's Installation table stays undefined and Parse's device notification are not working.

This is quite problematic for users of Android 9.

Is there a solution for this problem ?

I'm using com.parse:parse-android:1.16.7

**Comment by rodrigosmarques** [comment]
Hi,
see this guide. You need to add the Parse-FCM. Have you added?
https://github.com/parse-community/Parse-SDK-Android/tree/master/fcm

**Comment by g-martins** [comment]
Same here. It doesn't work from **Android O** or higher.
The application crashes when it tries to build the notification

`09-18 20:09:14.351 5620-5620/com.reelapps.RAShotListerApp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.reelapps.RAShotListerApp, PID: 5620
    java.lang.RuntimeException: Unable to start receiver com.parse.ParsePushBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification android.support.v4.app.NotificationCompat$Builder.build()' on a null object reference
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3388)
        at android.app.ActivityThread.access$1200(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification android.support.v4.app.NotificationCompat$Builder.build()' on a null object reference
        at com.parse.ParsePushBroadcastReceiver.onPushReceive(ParsePushBroadcastReceiver.java:174)
        at com.parse.ParsePushBroadcastReceiver.onReceive(ParsePushBroadcastReceiver.java:125)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3379)
        at android.app.ActivityThread.access$1200(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) `

**Comment by mmimeault** [comment]
We have the same 2 issues here. 
1. The crash (com.parse.ParsePushBroadcastReceiver.onPushReceive (ParsePushBroadcastReceiver.java:174))
2. The Token not saved.

But this is how I fixed those issues for now...
1. For now we added a safe around the method crashing. 
2. I call `ParseGCM.register(getApplicationContext());` when the app is launching. 
According to the Parse doc, nothing need to be done. But according to my tests, `com.google.android.gms.iid.InstanceID` service is not calling tokenRefresh on a new installation.. And only does it eventually.. with no guarantee when.

For the first issue, we can simply add a null check around the getNotification as the method actually return null in a specific case.
For the second issue, I didn't find the reason why the tokenRefresh is not called on the first register. Maybe it doesn't.. I didn't find the documentation about it. So for now I will keep my initial call as it does the job and does not generate any side effects.

**Comment by matdev** [comment]
Thanks Michael

I also have to register the device token when the app is launching. 
To do that, I call the parse installation's setDeviceToken() 

Note: This method cannot be called from the app, I've had to use reflection to call it.

**Comment by NicksonYap** [comment]
Solved it by adding the following manifest, it was removed recently (probably an error)

```
         <service
            android:name="com.parse.fcm.ParseFirebaseInstanceIdService"
            android:exported="true">
            <intent-filter>
               <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
         </service>
```

**Comment by mmimeault** [comment]
Ok thanks @NicksonYap I'll try that solution instead eventually.

**Comment by FridaySG** [comment]
Hey @NicksonYap I think the solution is rather:

```
        <service
            android:name="com.parse.fcm.ParseFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
```

**Comment by anhanh11001** [comment]
I'm also having this problem but it is an old app so it still use GCM, any ideas on how to fix it ?

**Comment by matdev** [comment]
> 
> 
> I'm also having this problem but it is an old app so it still use GCM, any ideas on how to fix it ?

Have you tried this method ?
https://github.com/parse-community/Parse-SDK-Android/issues/886#issuecomment-424631210

**Comment by mmimeault** [comment]
Thanks @matdev for the reference.
We are still doing that to support GCM with Android 9.

@anhanh11001 Just call `ParseGCM.register(context);` right after calling `Parse.initialize();`

This will make sure the GCM token is saved.

**Comment by matdev** [comment]
> I'm also having this problem but it is an old app so it still use GCM, any ideas on how to fix it ?

@anhanh11001 If you use a recent version of the Parse SDK (1.17+) , you should follow these instructions to use GCM: 
https://github.com/parse-community/Parse-SDK-Android/blob/master/gcm/README.md

**Comment by Jawnnypoo** [comment]
Better yet, update to FCM 😉 
https://github.com/parse-community/Parse-SDK-Android/blob/master/fcm/README.md
