### ISSUE TITLE
LinkedList NoSuchElementException on currentOperations

### ISSUE THREAD

**Issue by mmimeault** [parse-community/Parse-SDK-Android#910]
Hello,

We are getting some crashes at startup within the SDK when app launch. 
I do not have any STR but we have a detailed crash log.

```
Caused by java.util.NoSuchElementException
       at java.util.LinkedList.getLast(LinkedList.java:257)
       at com.parse.ParseObject.currentOperations(ParseObject.java:2939)
       at com.parse.ParseObject.hasChanges(ParseObject.java:1905)
       at com.parse.OfflineStore.saveLocallyAsync(OfflineStore.java:608)
```

I have a question before trying anything to resolve/propose a solution.

Do we expect the LinkedList operationSetQueue to always have something in it?

- If no, we should probably use a different method than "getLast" to determine the result of `hasChanges`, as it throw an exception when it is empty.
- If yes, can I get a small explanation in which case operationSetQueue could be empty (or should get fulfill)

We do not have much unique user crashes, but it seem that when a user crash once, he crash a lot and/or even always(?).

**Comment by mmimeault** [comment]
@rogerhu Do you have any idea?

**Comment by rogerhu** [comment]
I don't have full context of it.  I do see that most of the time it gets initialized with one here: https://github.com/parse-community/Parse-SDK-Android/blob/master/parse/src/main/java/com/parse/ParseObject.java#L166-L167

But I see here it can be emptied out:

https://github.com/parse-community/Parse-SDK-Android/blob/master/parse/src/main/java/com/parse/ParseObject.java#L166-L167

It does seem like though there is an assumption that if something has changes there ought to be something to be in the operation set queue...the saveEventually() is supposed to push all the stuff when stuff comes back online
