### ISSUE TITLE
ConcurrentModificationException in ParseObject.saveEventually

### ISSUE THREAD

**Issue by d-max** [parse-community/Parse-SDK-Android#913]
Hello. Thanks for library!
I use version `1.18.5` and I've got this exception trying to save set of objects:
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
	at java.util.HashMap$ValueIterator.next(HashMap.java:838)
	at com.parse.ParseTraverser.traverseInternal(ParseTraverser.java:87)
	at com.parse.ParseTraverser.traverse(ParseTraverser.java:137)
	at com.parse.ParseObject.collectDirtyChildren(ParseObject.java:2328)
	at com.parse.ParseObject.access$1400(ParseObject.java:49)
	at com.parse.ParseObject$36.visit(ParseObject.java:2320)
	at com.parse.ParseTraverser.traverseInternal(ParseTraverser.java:54)
	at com.parse.ParseTraverser.traverseInternal(ParseTraverser.java:88)
	at com.parse.ParseTraverser.traverse(ParseTraverser.java:137)
	at com.parse.ParseObject.collectDirtyChildren(ParseObject.java:2328)
	at com.parse.ParseObject.collectDirtyChildren(ParseObject.java:2337)
	at com.parse.ParseObject.saveEventually(ParseObject.java:1595)
        ...
```
It seems [this map](https://github.com/parse-community/Parse-SDK-Android/blob/master/parse/src/main/java/com/parse/ParseTraverser.java#L88) is not thread safe. 
Can you suggest fix or workaround for this problem, please? 
Thanks.

**Comment by Jawnnypoo** [comment]
Fixed in 1.19.0
