### ISSUE TITLE
Non SDK method used

### ISSUE THREAD

**Issue by nscherer** [parse-community/Parse-SDK-Android#924]
Starting with Android 9, Android is flagging uses of "non SDK" interfaces.  See here for more information:

https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces

The Parse SDK, via OkHttp, is using such.

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard;
        at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
        at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
        at java.lang.Class.getDeclaredMethodInternal(Native Method)
        at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
        at java.lang.Class.getMethod(Class.java:2063)
        at java.lang.Class.getMethod(Class.java:1690)
        at okhttp3.internal.platform.AndroidPlatform$CloseGuard.get(AndroidPlatform.java:370)
        at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.java:58)
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:260)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:201)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:78)
        at okhttp3.internal.platform.Platform.get(Platform.java:84)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:292)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:258)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1040)
        at com.parse.ParseHttpClient.<init>(ParseHttpClient.java:46)
        at com.parse.ParseHttpClient.createClient(ParseHttpClient.java:50)
        at com.parse.ParsePlugins.restClient(ParsePlugins.java:145)
        at com.parse.Parse.getEventuallyQueue(Parse.java:353)
        at com.parse.Parse.access$000(Parse.java:37)
        at com.parse.Parse$1.call(Parse.java:163)
        at com.parse.Parse$1.call(Parse.java:160)
        at bolts.Task$4.run(Task.java:357)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

My Parse dependency:

```
implementation 'com.github.parse-community.Parse-SDK-Android:parse:1.18.5'
```

Possibly just updating to the latest OkHttp will fix it, I don't know.  If not, I assume you would need to contact Square about the issue.

**Comment by Jawnnypoo** [comment]
You can update the version of OkHttp yourself if you just add it as a dependency (it will override our version so long as it is a later version). Here is the issue being tracked https://github.com/square/okhttp/issues/3980
