### ISSUE TITLE
Crash on startup on devices running Android API 19 

### ISSUE THREAD

**Issue by codyrotwein** [parse-community/Parse-SDK-Android#936]
I recently updated the Parse Android SDK to version 1.18.5. Now on devices running Android API 19, I'm seeing this crash upon startup:

`03-22 12:43:46.911 3186-3226/? E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: com.tsm.tri1025, PID: 3186
    java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
        at com.parse.ParseHttpClient.<init>(ParseHttpClient.java:46)
        at com.parse.ParseHttpClient.createClient(ParseHttpClient.java:50)
        at com.parse.ParsePlugins.restClient(ParsePlugins.java:145)
        at com.parse.Parse.getEventuallyQueue(Parse.java:353)
        at com.parse.Parse.access$000(Parse.java:37)
        at com.parse.Parse$1.call(Parse.java:163)
        at com.parse.Parse$1.call(Parse.java:160)
        at bolts.Task$4.run(Task.java:357)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015) 
        at com.parse.ParseHttpClient.<init>(ParseHttpClient.java:46) 
        at com.parse.ParseHttpClient.createClient(ParseHttpClient.java:50) 
        at com.parse.ParsePlugins.restClient(ParsePlugins.java:145) 
        at com.parse.Parse.getEventuallyQueue(Parse.java:353) 
        at com.parse.Parse.access$000(Parse.java:37) 
        at com.parse.Parse$1.call(Parse.java:163) 
        at com.parse.Parse$1.call(Parse.java:160) 
        at bolts.Task$4.run(Task.java:357) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) `

Here's the relevant lines in my grade file:
    implementation "com.github.parse-community.Parse-SDK-Android:parse:1.18.5"
    implementation "com.github.parse-community.Parse-SDK-Android:fcm:1.18.5"

Is there any way to use this version of the Parse SDK while still allowing the minimum android SDK to be 19? It seems to be caused by Parse's OkHttp version.

**Comment by Jawnnypoo** [comment]
Another dependency you are using is probably updating OkHttp 3.14+, which only supports 21+. You should run `./gradlew app:dependencies` where `app` is the name of your application module and scan through the results to see which dependency you use is bringing OkHttp to that version. Or alternatively, specify OkHttp as a dependency in your project and lock it down to 3.13.x

**Comment by codyrotwein** [comment]
You're right. It turned out that Parse wasn't to blame. Had this dependency that was also using OKHTTP: 
implementation 'com.google.android.exoplayer:extension-okhttp:r2.0.1'
