### ISSUE TITLE
Parse server and Okhttp crash on lookup

### ISSUE THREAD

**Issue by Sulfkain** [parse-community/Parse-SDK-Android#938]
Hello,
I have received some crashes on Crashlytics due okhttp and bad handling errors on ParseSDK.

I use the parseVersion = "1.18.5"
I will update to the new one, but seems the latest versions didn't fix any related with this, so seems logical it will still happening on latest versions.

This is the log:
```
Caused by java.net.UnknownHostException: Unable to resolve host "parse.frysbe.com": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
       at java.net.InetAddress.getAllByName(InetAddress.java:1154)
       at okhttp3.Dns$1.lookup(Dns.java:40)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:142)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall.execute(RealCall.java:77)
       at com.parse.ParseHttpClient.executeInternal(ParseHttpClient.java:71)
       at com.parse.ParseHttpClient.execute(ParseHttpClient.java:57)
       at com.parse.ParseRequest$3.then(ParseRequest.java:133)
       at com.parse.ParseRequest$3.then(ParseRequest.java:130)
       at bolts.Task$15.run(Task.java:917)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeAfterTask(Task.java:908)
       at bolts.Task.continueWithTask(Task.java:715)
       at bolts.Task.continueWithTask(Task.java:726)
       at bolts.Task$13.then(Task.java:818)
       at bolts.Task$13.then(Task.java:806)
       at bolts.Task$15.run(Task.java:917)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

I have readed on other places, the problem is okhttp when this error raises, not call the onError callback but crash.
But seems to be fixeable with some changes
I attach the info i readed if it helps :)
https://github.com/square/retrofit/issues/1829
https://github.com/square/okhttp/issues/3122

The full log:
[OkhttpCrash_ParseServer.log](https://github.com/parse-community/Parse-SDK-Android/files/3042736/OkhttpCrash_ParseServer.log)

Thank you!

**Comment by Sulfkain** [comment]
Any update? Could this be fixed?
Thank you
