### ISSUE TITLE
Handling error 503 - bad json response

### ISSUE THREAD

**Issue by Sulfkain** [parse-community/Parse-SDK-Android#949]
Hello,
I was looking on issues and doc about handling server errors on client side, but I didn't see any info about.
Nor here on issues, nor doc, nor stackoverflow about Parse.

So, I'm getting sometimes 503 on server and app crash due the bad handling with this log:
```
ParseRESTCommand.java line 299
com.parse.ParseRESTCommand.onResponseAsync
Caused by com.parse.ParseRequest$ParseRequestException: bad json response
       at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:288)
       at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:309)
       at com.parse.ParseRequest$3.then(ParseRequest.java:134)
       at com.parse.ParseRequest$3.then(ParseRequest.java:130)
       at bolts.Task$15.run(Task.java:917)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeAfterTask(Task.java:908)
       at bolts.Task.continueWithTask(Task.java:715)
       at bolts.Task.continueWithTask(Task.java:726)
       at bolts.Task$13.then(Task.java:818)
       at bolts.Task$13.then(Task.java:806)
       at bolts.Task$15.run(Task.java:917)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

--------

Caused by org.json.JSONException: Value <html><body><h1>503 of type java.lang.String cannot be converted to JSONObject
       at org.json.JSON.typeMismatch(JSON.java:112)
       at org.json.JSONObject.<init>(JSONObject.java:163)
       at org.json.JSONObject.<init>(JSONObject.java:176)
       at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:299)
       at com.parse.ParseRequest$3.then(ParseRequest.java:134)
       at com.parse.ParseRequest$3.then(ParseRequest.java:130)
       at bolts.Task$15.run(Task.java:917)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeAfterTask(Task.java:908)
       at bolts.Task.continueWithTask(Task.java:715)
       at bolts.Task.continueWithTask(Task.java:726)
       at bolts.Task$13.then(Task.java:818)
       at bolts.Task$13.then(Task.java:806)
       at bolts.Task$15.run(Task.java:917)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

We have the last (1.20.0) client SDK and happens (obviously) on any device and Android version.

The question is, how can I handle this error to avoid crash on app and just show some network error to the user?.

Thanks.

**Comment by mtrezza** [comment]
Also on 1.20.0 but the app does not crash. Are you sure the crash is caused by Parse SDK and not because your parsing of the reserver response fails?

**Comment by Sulfkain** [comment]
Hello @mtrezza,
I have this trace from crashlytics as Crash and as NON-FATAL, the last one I logged explicitly on crashlytics, so I suppose there are some crashes on some circumstances and other as just ParseErrors which I could handle normally and I already logged.

I have re-checked my services calls and I check if data is casteable and/or null.
I do it with Kotlin like so:
```
        val infoList = info as? ArrayList<ParseObject>
        if (infoList == null) return null
```

So this piece of code, in theory it's impossible to crash because it just a check, if the data from server is bad, this just will result on null and I already handle null values from server with some feedback error.

And if the problem was in my code I supose crashlytics will point to some part of my code which throw the exception, but seems to be a internal part from Parse while it tries to parse the response to a valid ParseObject.

If you need I will test something or you have some idea why this could happen and try a solution. I'm really happy to try to test and fix it :).

Thank you.

**Comment by mtrezza** [comment]
Crashlytics' `Non Fatals` do not crash the app. These errors are merely logged.

**Comment by Sulfkain** [comment]
Finally I have found the problem was on my code, just on a little part, but not on Parse, so sorry for this and thanks for the support :)
