### ISSUE TITLE
W/System.err: com.parse.ParseRequest$ParseRequestException: i/o failure

### ISSUE THREAD

**Issue by ziyang-ji** [parse-community/Parse-SDK-Android#968]
Hello, I am getting the following exception when signing up users and logging in. I assume it's because of connection with parse server. I am using 1.20.0 version of parse Android SDK. Please help me look at it. Thanks!
W/System.err: com.parse.ParseRequest$ParseRequestException: i/o failure
        at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:288)
        at com.parse.ParseRequest$2.then(ParseRequest.java:142)
W/System.err:     at com.parse.ParseRequest$2.then(ParseRequest.java:136)
        at bolts.Task$15.run(Task.java:917)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
W/System.err: Caused by: java.net.UnknownServiceException: CLEARTEXT communication to 54.152.84.61 not permitted by network security policy
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at com.parse.ParseHttpClient.executeInternal(ParseHttpClient.java:71)
        at com.parse.ParseHttpClient.execute(ParseHttpClient.java:57)
        at com.parse.ParseRequest$3.then(ParseRequest.java:133)
W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:130)
        at bolts.Task$15.run(Task.java:917)
        at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
        at bolts.Task.completeAfterTask(Task.java:908)
        at bolts.Task.continueWithTask(Task.java:715)
W/System.err:     at bolts.Task.continueWithTask(Task.java:726)
        at bolts.Task$13.then(Task.java:818)
        at bolts.Task$13.then(Task.java:806)
    	... 4 more

**Comment by Jawnnypoo** [comment]
Yep, change over to use HTTPS for your server calls.
