### ISSUE TITLE
Crash when calling ParseUser before Parse init

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Android#981]
#### Issue

App crashes when calling `ParseUser.getCurrentUser();` before initializing Parse SDK.

#### Solution
App should not crash?

#### Log

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File com.parse.ParsePlugins.getParseDir()' on a null object reference
        at com.parse.Parse.getParseDir(Parse.java:254)
        at com.parse.ParseCorePlugins.getCurrentUserController(ParseCorePlugins.java:124)
        at com.parse.ParseUser.getCurrentUserController(ParseUser.java:76)
        at com.parse.ParseUser.getCurrentUser(ParseUser.java:235)
        at com.parse.ParseUser.getCurrentUser(ParseUser.java:223)
```

#### Env
- Parse SDK 1.21.0

**Comment by mtrezza** [comment]
Closed, it seems to be intended behavior of Parse SDK to throw an exception when not initialized. Could be more elegant, but it's not an issue.
